### ISSUE TITLE
Task: Invite Mario Carpo to lecture

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ame6201-organisation#25]
# Task Description
We invite Mario Carpo to lecture. 
Shin had contact with M. Carpo by email and in person in 2019. 

# List of actions
- [ ] Action: draft invitation email
- [ ] Action: Email M. Carpo

**Comment by sjinko** [comment]
Hi @danecas, I can write to M. Carpo if you would like or you could do it for DVS / BH since it's the venue. 

I can also "pre contact" him if necessary. 

I met with him in 2019 and have his personal email. He is good friend with Cache and Ortelli.

**Comment by danecas** [comment]
HI Shin,

Yes, please you can write to him, maybe it is good to do it directly. I can
then add some context in a second more formal email if necessary. Otherwise
I can write a paragraph ands send it to you, as you think it's best.

Darío Negueruela del Castillo
